# Generated by Django 5.2.1 on 2025-05-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='option_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='options',
            name='option_text_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='options',
            name='option_text_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
