# Generated by Django 5.2.1 on 2025-05-20 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udemy_app', '0002_alter_options_option_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='certificate_url',
            new_name='certificate',
        ),
    ]
